"""rules: is_published + editing lock

Revision ID: 6846bc59f1da
Revises: 8d361f285409
Create Date: 2026-04-22 14:29:55.601976

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6846bc59f1da"
down_revision: str | None = "8d361f285409"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rule_editing_locks",
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("admin_id", sa.UUID(), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("slot"),
    )
    # Новое поле с server_default=false, чтобы upgrade не упал на существующих строках
    op.add_column(
        "rules",
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Все правила, существовавшие до этой миграции (seed), считаются опубликованными
    op.execute("UPDATE rules SET is_published = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "is_published")
    op.drop_table("rule_editing_locks")
    # ### end Alembic commands ###
