"""init schema

Revision ID: 8d361f285409
Revises:
Create Date: 2026-04-22 12:34:27.465632

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d361f285409"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_directions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("example_jobs", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "ck_courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "ML",
                "DEVELOPMENT",
                "SECURITY",
                "TESTING",
                "MANAGEMENT",
                "OTHER",
                name="ckcoursecategory",
            ),
            nullable=False,
        ),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "competencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "PROGRAMMING",
                "MATH",
                "DATA",
                "ML",
                "ENGINEERING",
                "NETWORKS",
                "SYSTEM",
                "APPLIED",
                name="competencycategory",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_competencies_tag"), "competencies", ["tag"], unique=True)
    op.create_table(
        "disciplines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("MANDATORY", "ELECTIVE", "CHOICE", name="disciplinetype"),
            nullable=False,
        ),
        sa.Column("control_form", sa.String(length=50), nullable=False),
        sa.Column("department", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column(
            "group",
            sa.Enum(
                "CK_PROGRAMS",
                "BASIC_UNIVERSAL",
                "TECHNOPARK",
                "DISCIPLINE_FOCUS",
                "COURSEWORK",
                "WARNINGS",
                "STRATEGY",
                name="rulegroup",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("condition", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendation", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("STUDENT", "ADMIN", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=True),
        sa.Column(
            "career_goal",
            sa.Enum(
                "ML",
                "BACKEND",
                "FRONTEND",
                "CYBERSECURITY",
                "SYSTEM",
                "DEVOPS",
                "MOBILE",
                "GAMEDEV",
                "QA",
                "ANALYTICS",
                "UNDECIDED",
                name="careergoal",
            ),
            nullable=True,
        ),
        sa.Column(
            "technopark_status",
            sa.Enum("NONE", "BACKEND", "FRONTEND", "ML", "MOBILE", name="techparkstatus"),
            nullable=True,
        ),
        sa.Column(
            "workload_pref",
            sa.Enum("LIGHT", "NORMAL", "INTENSIVE", name="workloadpref"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "career_competencies",
        sa.Column("career_direction_id", sa.UUID(), nullable=False),
        sa.Column("competency_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["career_direction_id"],
            ["career_directions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
        ),
        sa.PrimaryKeyConstraint("career_direction_id", "competency_id"),
    )
    op.create_table(
        "ck_course_competencies",
        sa.Column("ck_course_id", sa.UUID(), nullable=False),
        sa.Column("competency_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ck_course_id"],
            ["ck_courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
        ),
        sa.PrimaryKeyConstraint("ck_course_id", "competency_id"),
    )
    op.create_table(
        "ck_course_prerequisites",
        sa.Column("ck_course_id", sa.UUID(), nullable=False),
        sa.Column("competency_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ck_course_id"],
            ["ck_courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
        ),
        sa.PrimaryKeyConstraint("ck_course_id", "competency_id"),
    )
    op.create_table(
        "discipline_competencies",
        sa.Column("discipline_id", sa.UUID(), nullable=False),
        sa.Column("competency_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competency_id"],
            ["competencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["discipline_id"],
            ["disciplines.id"],
        ),
        sa.PrimaryKeyConstraint("discipline_id", "competency_id"),
    )
    op.create_table(
        "focus_advices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("discipline_id", sa.UUID(), nullable=False),
        sa.Column("career_direction_id", sa.UUID(), nullable=False),
        sa.Column("focus_advice", sa.Text(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["career_direction_id"], ["career_directions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["discipline_id"], ["disciplines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discipline_id", "career_direction_id", name="uq_focus_disc_career"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "student_completed_ck",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ck_course_id", sa.UUID(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ck_course_id"], ["ck_courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "ck_course_id"),
    )
    op.create_table(
        "student_grades",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("discipline_id", sa.UUID(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["discipline_id"], ["disciplines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "discipline_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_grades")
    op.drop_table("student_completed_ck")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("focus_advices")
    op.drop_table("discipline_competencies")
    op.drop_table("ck_course_prerequisites")
    op.drop_table("ck_course_competencies")
    op.drop_table("career_competencies")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("rules")
    op.drop_table("disciplines")
    op.drop_index(op.f("ix_competencies_tag"), table_name="competencies")
    op.drop_table("competencies")
    op.drop_table("ck_courses")
    op.drop_table("career_directions")
    # ### end Alembic commands ###
